### ISSUE TITLE
Zpětná vazba

### ISSUE THREAD

**Issue by JanaNovotna** [Justisedli/PROJEKT-Sluzby#1]
Ahoj! 

Super, funguje to a vypadá to dobře :) 
Mám pár tipů (ať napíšu alespoň něco :D) : 
Místo divů můžeš použít na jednotlivé části "section" (ty divy, u kterých máš třídy vršek, druha, treti), ikonky by pak šli udělat i pomocí seznamu. 
Oceňuji, že si našla a použila pseudoprvek ::after 

Jinak u těch media queries pak píšeš jen to, co se mění. Např. u třídy "trojice", jakmile je to jednou display:flex je to pořád display flex dokud neřekneš jinak. Přepíšeš jen, že to má jinou velikost nebo jak je to seřazené. Vyskytuje se to tam vícekrát. Za a) to ušetří práci a zábava) kód bude malinko kratší a o fous přehlednější. 

Taky kolegové v budoucnu ocení, když budeš psát věci v podobném pořadí - jednou máš justify-content na začátku, jednou na konci. Upřímně  je to fakt detail, ale chvilku mi trvalo se v kódu zorientovat. 

Ale jinak dobrý! Díky! 

Janča

**Comment by Justisedli** [comment]
Ahoj, moc děkuji za zpětnou vazbu :)
